### ISSUE TITLE
1.1 Crashes hard

### ISSUE THREAD

**Issue by mbinkhorst** [KAMIKAZEUA/NativeDisplayBrightness#3]
Completely locks up the mac when it tries to load 1.1. Version 1.0 is working without a hitch.

Hackintosh on 10.13.3, with latest Lilu etc.

Other people have this issue as well:
https://www.reddit.com/r/hackintosh/comments/7wce35/great_new_fork_of_native_display_brightness_with/

Let me know if you need more info.

**Comment by Anywhere-Music-Player** [comment]
> Other people have this issue as well: 

Nobody there has a locks up of their Mac. There was a crash for some users at launching, thats because this app target is macOS version: 10.12.4 or later. That wasn't specified last time.

I've used Lilu and other patches and it works for 10.13.3 and 10.13.4 for me, using every day. 

Only way to try to debug this - you need to install [Xcode](https://developer.apple.com/xcode/) and open `NativeDisplayBrightness.xcodeproj` and `build&run` this app, to see whats happening. Xcode probably can show some crash.

**Comment by mbinkhorst** [comment]
Hm ok. I'll try building/running with xcode and see what happens. Thanks!
