### ISSUE TITLE
Increasing brightness over 100%?

### ISSUE THREAD

**Issue by Simbe90** [KAMIKAZEUA/NativeDisplayBrightness#5]
This app works great, but is there a way to increase the brightness for over 100%? If I set my display manually to full brightness, the app shows 255%, but the moment I move the slider, the screen goes dimmer and I can't increase it above 100%.

**Comment by Anywhere-Music-Player** [comment]
Thats fun actually. Looks like your monitor work in a very weird way. Whats model? 
However, I can tell you that it's will not be possible for me to fix this, because I simply can't buy same monitor.. Also, I've just added GUI for this app. Possible fix should be done by initial app creator - https://github.com/Bensge/NativeDisplayBrightness

**Comment by Simbe90** [comment]
Thanks! I'm able to set it past 100 on an app called Brightness Menulet, but it lacks all the features. And it's a HP ZR30w connected via USB-C <-> DisplayPort cable.
![screen shot 2018-07-05 at 20 24 25](https://user-images.githubusercontent.com/20671145/42338113-6f8c2268-8091-11e8-8312-e2580271fe7f.png)
